---

kind: Service
apiVersion: v1
metadata:
  name: docs-ubuntu-com-phone
spec:
  selector:
    app: docs.ubuntu.com-phone
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http

---

kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: docs-ubuntu-com-phone
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: docs.ubuntu.com-phone
    spec:
      containers:
        - name: docs-ubuntu-com-phone
          image: prod-comms.docker-registry.canonical.com/docs.ubuntu.com-phone:${TAG_TO_DEPLOY}
          ports:
            - name: http
              containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 3
            successThreshold: 3
          livenessProbe:
            exec:
              command:
              - /bin/sh
              - -c
              - /bin/netstat -lp | grep :80
            initialDelaySeconds: 5
            periodSeconds: 5

---
